env:
  node: true
parserOptions:
  ecmaVersion: 2020
extends:
  - airbnb-base
rules:
  import/extensions: 0
  global-require: 0
  import/no-extraneous-dependencies:
    - error
    -
      packageDir: ./
